### ISSUE TITLE
Tracking: Add/Improve integration tests

### ISSUE THREAD

**Issue by adetokunbo** [adetokunbo/haskell-overridez#25]
#24 was a good start, but there should be a few more tests with some more detailed checks.

**Comment by adetokunbo** [comment]
FYI: #33 made the integration tests much better.  They were actually incorrect because they did not verify that the overloads were used; #33 fixed that.

**Comment by adetokunbo** [comment]
A list of things that the integrations test should verify - when all of these are done, this issue can be closed. 

__Update__ #38 ticks all the boxes!

### Saving override configuration
- [x] overrides for a project at a subpath of any git url can be saved as nix expressions
- [x] 'known' cabal options can be saved along with either github json or nix expressions
- [x] override configuration can be saved to an alternate directory
- [x] overrides for a project at a github url can be saved as a json github repository descriptor
- [x] overrides for a project at any git url can be saved as nix expressions

### Using override config
- [x] the requested cabal options are applied to the project's nix derivation 
- [x] overrides configured from github json are correctly loaded by the project's nix derivation
- [x] overrides configured by nix expressions are correctly loaded by the project's nix derivation

### Fetching
- [x] `fetch` can get configuration from any repository and save to an alternate directory
- [x] `fetch` can get configuration from a remote git repository and saves it in the current directory
- [x] `fetch` can get configuration from a local git repository and saves it in the current directory
